name: Test

on:
  push:
  pull_request:

# Cancel previous runs for PRs but not pushes to main
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: nix develop --command {0}

jobs:
  test:
    runs-on: codeberg-small
    container:
      image: codeberg.org/polyfloyd/nix-ci:latest
    steps:
      - uses: actions/checkout@v4
      - name: Populate /nix/store
        run: echo done
      - name: Format
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy --all-features -- -Dwarnings
      - name: Check for debug macro
        run: "! grep -r 'dbg!' ./src"
      - name: Build
        run: cargo build --all-features
      - name: Tests
        run: cargo test --all-features

  conventional-commits:
    if: github.event_name == 'pull_request'
    runs-on: codeberg-tiny
    container:
      image: codeberg.org/polyfloyd/nix-ci:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Populate /nix/store
        run: echo done
      - run: cz check --rev-range origin/${{ github.base_ref }}..HEAD
